### ISSUE TITLE
Picosheet demo broken by more strict word rules

### ISSUE THREAD

**Issue by greggirwin** [red/code#21]
There's a placeholder col header with #" " as the text, which to word! doesn't like when combined with a numeric digit to create the cell ref name. If you replace [#" "] with [#"_"]for now, it will work again.

**Comment by Oldes** [comment]
I closed my fix as I noticed that it was already fixed by Nenad in this commit: https://github.com/red/code/commit/9b7fb4fae1781cc98a46e6f0b2aa3546537dde4d
