### ISSUE TITLE
Can't run anything

### ISSUE THREAD

**Issue by theideasmith** [red/code#3]
I was really excited to hear about this language because I had envisioned something in the past, however nothing will run on my macbook air with the red-061binary. 

For instance, when I try to run the calculator demo I get: 

```
*** Script Error: view has no value
*** Where: catch
```

**Comment by dockimbel** [comment]
Hi, welcome. The MacOSX port of the GUI is not yet finished sorry, so it's not part of the 0.6.1 release on Mac. Though, all the non-GUI features (including the reactive framework) are there and should work fine on all the supported platforms.

One option some of Red users on MacOSX are currently using for running GUI apps is [Wine](https://www.winehq.org/).

You are welcome to join us on [Gitter](https://gitter.im/red/red) for chatting with us about Red.
