### ISSUE TITLE
Picosheet on W7 skips initial update

### ISSUE THREAD

**Issue by hiiamboris** [red/code#94]
See how I have to click on cells else they won't kick off
![](https://i.gyazo.com/d62db1d3fa4ed2894618fb84d4f86048.gif)

**Comment by hiiamboris** [comment]
Apparently a regression. I have a May 21, 2020 build that's working and May 27, 2020 build that is like above. `face/text` -> `face/data` mechanics doesn't work anymore before the window gets shown. Can't pinpoint the exact commit that caused it though.

**Comment by hiiamboris** [comment]
Also FYI:
https://github.com/red/code/blob/8bc261749fbf9920e2155c077411c64e7c1bdae8/Showcase/picosheet.red#L69
`do f/data` is extraneous: `react` will `do` it anyway.

**Comment by greggirwin** [comment]
Is this still borked for you @hiiamboris ?

**Comment by hiiamboris** [comment]
It's even worse right now, on W10 though. No amount of clicking fixes it.

**Comment by hiiamboris** [comment]
`math has no refinement called safe` it says

**Comment by hiiamboris** [comment]
@9214 should be in the know I presume

**Comment by 9214** [comment]
https://github.com/red/red/pull/4332

> At least Picosheet demo will need an update after this PR is merged.

Better now than never I guess 🤷‍♂️ 

> face/text -> face/data mechanics doesn't work anymore before the window gets shown. Can't pinpoint the exact commit that caused it though.

https://github.com/red/red/issues/3606#issuecomment-580351889?

**Comment by dockimbel** [comment]
Should be working fine now. Can you confirm?

**Comment by hiiamboris** [comment]
No access to W7 atm :/

**Comment by hiiamboris** [comment]
On W10 it's fine though, so I guess this can be closed. Found a bit different glitch:
![](https://i.gyazo.com/574c07d559e52e87627a8382f3619419.gif)

I suppose that's because it recomputes the cell after textifying its content.

**Comment by dockimbel** [comment]
It's `#UND` if you are editing one of its source cells, that's how it is supposed to work.

**Comment by hiiamboris** [comment]
OK then
