### ISSUE TITLE
Missing %definitions.reds

### ISSUE THREAD

**Issue by G-o-r-d** [red/code#95]
I was trying to compile "SQLite3.red" using: red-064 -c SQLite3.red in Windows 10 OS, when it ended with:
```
Compiling to native code...
*** Loading Error: file access error: %definitions.reds
*** in file: %/c/.../Programming/Rebol/RED/SQLite/Oldies/SQLite3.reds
*** at line: 15
```
I found the 'definitions.reds' file in 'red/code - library/OS' and added it to the same directory as the SQLite3.red I was trying to compile, but I am still getting the error message.

Any help would be appreciated. TIA

(Background: I have written a nearly complete accounting system in Rebol3 {many thousands of lines of Rebol3 code} and it uses MySQL with the DB on a remote server.  It works okay, but I wanted to start converting it to RED and SQLite. 

I've been wanted to move to RED for years but still waiting for 'Network I/O' till I found this SQLite.red)

**Comment by G-o-r-d** [comment]
I found the 'definitions.reds' file in 'red/code - library/OS' and added it to the same directory, as the SQLite3.red I was trying to compile, but I am still getting the error message.
Any help would be appreciated.  TIA

**Comment by Oldes** [comment]
You must have wrong paths. Where is the file where you are including the [`definitions.reds`](https://github.com/red/code/blob/master/Library/os/definitions.reds) file?
In the SQLite code it is [being included there](https://github.com/red/code/blob/aed67bbde592db4129e6af1219c6bf88f4c515a1/Library/SQLite/SQLite3.reds#L15) and it expects same file structure like the red/code repository.

If you have the file in the same place like `SQLite3.red`, than you must modify above mentioned line in [`SQLite3.reds`](https://github.com/red/code/blob/master/Library/SQLite/SQLite3.reds).

**Comment by G-o-r-d** [comment]
Thank you.  I don't know how I missed that.  It compiled without errors, (using the -r flag).
```
Compiling c:\Users\gord2\Gords Documents\Programming\Rebol\RED\SQLite\Oldies\SQLite3-test.red ...
...compilation time : 2115 ms

Target: MSDOS

Compiling to native code...
...compilation time : 61681 ms
...linking time     : 1913 ms
...output file size : 657408 bytes
...output file      : c:\Users\gord2\Gords Documents\Programming\Rebol\RED\SQLite\Oldies\SQLite3-test.exe
```
(Immediately after compiling, I got a Windows10 warning about a security threat and it quarantined the file.  I released it from quarantine and it immediately showed up in the file list.)
Running from a windows command prompt I get the following error:
![image](https://user-images.githubusercontent.com/9373228/92044994-afb64480-ed3c-11ea-8818-5171f8437a49.png)
So I took another look at the code and saw that SQLite3.reds requires the "sqlite3.dll" so I checked my path and my SQLite directory is part of my windows path, (version 3.33.0 2020-08-14).  Nevertheless, I copied the sqlite3.dll to this RED SQLite-test directory and recompiled the script again using: 'red-064.dll -c -r SQLite3-test.red', it produced another executable, (this time without the Windows10 security warning), but now getting this message.
![image](https://user-images.githubusercontent.com/9373228/92048163-39b5db80-ed44-11ea-9214-2c83eb8de493.png)
I downloaded and installed MS DirectX End-User Runtime ("installs a number of runtime libraries from the legacy DirectX SDK ... Version 9.29.1974 - 2011-04-18, without modifying the Direct X Runtime installed on your Windows OS in any way... This DirectX End-User Runtime does not change the version of DirectX, but does install a number of optional side-by-side technologies from the legacy DirectX SDK that are used by some older games.").  Then I downloaded and installed .NET Framework 4.7.2 Runtime, but it was already installed.

Any more ideas about what I'm doing wrong?

**Comment by G-o-r-d** [comment]
I looked up the error code, (0xc000007b), and this led me to check my system health.  I've been using SFC.ex and DISM.exe and it reports a problem with my system that it is unable to fix.
Therefore, it doesn't appear to be a RED code problem.
